# Generated by Django 5.0.6 on 2024-10-09 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notify', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
